// @vitest-environment node
// The region bake (bake.ts): the canonical seed's costly searches, replayed at boot. It must be
// exactly what a fresh build computes, or the world a visitor sees drifts from the code. To
// regenerate after changing the builder (or the planet's shape):
//   LB_REGION_BAKE=1 pnpm vitest run components/littlebig/world/region/bake.spec.ts
//
// "Exactly" only holds on the kind of machine that wrote the bake: V8's Math.sin, cos, tan, atan2,
// acos, exp, log and pow differ in the last bits between x86-64 and arm64 (pow between Node majors
// too), and one last-bit difference can flip a search's later choices. So the bake records a
// signature of those functions. Where it matches, the fresh build must reproduce the bake bit for
// bit; elsewhere (CI's x86-64 runners for a bake written on an arm64 Mac) each search is recomputed
// from the bake's own inputs and must agree to within float noise.

import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { SEED } from '../config';
import { createPlanet } from '../planet';
import type { Drift, Memo } from './bake';
import { REGION_BAKE, REGION_BAKE_MATH } from './baked';

const memoOf = (r: unknown) => (r as { memo: Memo }).memo;

/** A hash of this engine's transcendental Math results (see the header). */
function mathSignature(): string {
  const f = new Float64Array(1);
  const w = new Uint32Array(f.buffer);
  let h = 0x811c9dc5;
  const mix = (x: number) => {
    f[0] = x;
    h = Math.imul(h ^ w[0], 0x01000193);
    h = Math.imul(h ^ w[1], 0x01000193);
  };
  for (let i = 1; i <= 4000; i++) {
    const x = i * 0.0137 - 27.4;
    const s = Math.sin(x);
    mix(s);
    mix(Math.cos(x));
    mix(Math.tan(x));
    mix(Math.atan2(x, 1.3));
    mix(Math.asin(s));
    mix(Math.acos(s));
    mix(Math.atan(x));
    mix(Math.exp(x / 9));
    mix(Math.log(i));
    mix(Math.pow(i * 0.01, 1.37));
  }
  return (h >>> 0).toString(16);
}

/** Float noise an entry may carry on another kind of machine: one step of its encoding. */
function withinNoise(d: Drift): boolean {
  if (d.got !== d.len) return false;
  return d.enc === 'mm16' ? d.max <= 0.0011 : d.enc === 'cm16' ? d.max <= 0.011 : d.max <= 1e-6;
}

const sameMath = mathSignature() === REGION_BAKE_MATH;

describe('region bake', () => {
  it('is what a fresh build computes (else regenerate it)', { timeout: 60000 }, () => {
    const stale = 'world/region/baked.ts is stale: run LB_REGION_BAKE=1 pnpm vitest run components/littlebig/world/region/bake.spec.ts';
    if (process.env.LB_REGION_BAKE === '1') {
      const fresh = createPlanet(SEED, { regionBake: null }).region;
      // (the ferries' searches are memoised on their first read: read them before the dump)
      void fresh.ferries;
      const dump = memoOf(fresh).dump();
      const file = path.join(path.dirname(new URL(import.meta.url).pathname), 'baked.ts');
      fs.writeFileSync(
        file,
        `// GENERATED by world/region/bake.spec.ts (LB_REGION_BAKE=1 pnpm vitest run components/littlebig/world/region/bake.spec.ts):\n` +
          `// the region build's costly searches for the canonical seed (world/region/bake.ts). Do not edit.\n` +
          `export const REGION_BAKE =\n  '${dump}';\n` +
          `// The Math signature of the engine that wrote it (bake.spec.ts; tests only).\n` +
          `export const REGION_BAKE_MATH = '${mathSignature()}';\n`,
      );
      return;
    }
    if (sameMath) {
      const fresh = createPlanet(SEED, { regionBake: null }).region;
      void fresh.ferries;
      expect(memoOf(fresh).dump() === REGION_BAKE, stale).toBe(true);
      return;
    }
    // Another engine: replay the bake, recomputing every search from the bake's inputs.
    const verified = createPlanet(SEED, { regionVerify: true }).region;
    void verified.ferries;
    const { misses, drift } = memoOf(verified).stats;
    expect(misses, stale).toBe(0);
    expect(drift.filter((d) => !withinNoise(d)), stale).toEqual([]);
  });

  it('replays every search from it, and builds the same region', { timeout: 60000 }, () => {
    const baked = createPlanet(SEED).region;
    expect(memoOf(baked).stats.misses).toBe(0);
    expect(baked.ferries.length).toBeGreaterThanOrEqual(2);
    expect(memoOf(baked).stats.misses).toBe(0);
    const fresh = createPlanet(SEED, { regionBake: null }).region;
    const places = (r: typeof fresh) => r.settlements.map((s) => [s.id, s.dir.x, s.dir.y, s.dir.z, s.h] as const);
    const roads = (r: typeof fresh) => r.edges.map((e) => [e.name, e.centre.length, e.centre.h[0]] as const);
    if (sameMath) {
      expect(places(baked)).toEqual(places(fresh));
      expect(roads(baked)).toEqual(roads(fresh));
      return;
    }
    // (another engine's fresh build may take a last-bit-different turn in a search: the same places
    // and roads, to the centimetre)
    const near = (a: readonly (string | number)[], b: readonly (string | number)[]) => a.every((v, k) => (typeof v === 'string' ? v === b[k] : Math.abs(v - (b[k] as number)) < 0.01));
    expect(baked.settlements.length).toBe(fresh.settlements.length);
    expect(baked.edges.length).toBe(fresh.edges.length);
    const pb = places(baked), pf = places(fresh), rb = roads(baked), rf = roads(fresh);
    expect(pb.filter((p, k) => !near(p, pf[k]))).toEqual([]);
    expect(rb.filter((r, k) => !near(r, rf[k]))).toEqual([]);
  });
});
