// @vitest-environment node
// The region bake (bake.ts): the canonical seed's costly searches, replayed at boot. It must be
// exactly what a fresh build computes, or the world a visitor sees drifts from the code. To
// regenerate after changing the builder (or the planet's shape):
//   LB_REGION_BAKE=1 pnpm vitest run components/littlebig/world/region/bake.spec.ts

import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { SEED } from '../config';
import { createPlanet } from '../planet';
import type { Memo } from './bake';
import { REGION_BAKE } from './baked';

const memoOf = (r: unknown) => (r as { memo: Memo }).memo;

describe('region bake', () => {
  it('is what a fresh build computes (else regenerate it)', { timeout: 60000 }, () => {
    const fresh = createPlanet(SEED, { regionBake: null }).region;
    const dump = memoOf(fresh).dump();
    if (process.env.LB_REGION_BAKE === '1') {
      const file = path.join(path.dirname(new URL(import.meta.url).pathname), 'baked.ts');
      fs.writeFileSync(
        file,
        `// GENERATED by world/region/bake.spec.ts (LB_REGION_BAKE=1 pnpm vitest run components/littlebig/world/region/bake.spec.ts):\n` +
          `// the region build's costly searches for the canonical seed (world/region/bake.ts). Do not edit.\n` +
          `export const REGION_BAKE =\n  '${dump}';\n`,
      );
      return;
    }
    expect(dump === REGION_BAKE, 'world/region/baked.ts is stale: run LB_REGION_BAKE=1 pnpm vitest run components/littlebig/world/region/bake.spec.ts').toBe(true);
  });

  it('replays every search from it, and builds the same region', { timeout: 60000 }, () => {
    const baked = createPlanet(SEED).region;
    expect(memoOf(baked).stats.misses).toBe(0);
    const fresh = createPlanet(SEED, { regionBake: null }).region;
    expect(baked.settlements.map((s) => [s.id, s.dir.x, s.dir.y, s.dir.z, s.h])).toEqual(fresh.settlements.map((s) => [s.id, s.dir.x, s.dir.y, s.dir.z, s.h]));
    expect(baked.edges.map((e) => [e.name, e.centre.length, e.centre.h[0]])).toEqual(fresh.edges.map((e) => [e.name, e.centre.length, e.centre.h[0]]));
  });
});
