// The region build's memo (R1): its costly searches (settlement and airport sites, A* routes, terrain
// samples along roads and round pads) are cached decisions. A build for the canonical seed replays
// them from a baked string (world/region/baked.ts, generated by bake.spec.ts) and only does the cheap
// deterministic work itself (towns' streets, smoothing, grading, the network, the carve grid), which
// keeps getRegion() inside its budget on the terrain's first-frame path.
//
// Safety: each entry stores a hash of the INPUTS it was computed from (anchor positions, endpoints,
// the path it sampled…, rounded to 1e-6 so another JS engine's last-bit differences still match) and
// the whole bake a fingerprint of the base terrain; an entry whose inputs differ, or a bake for
// another terrain, is recomputed live (correct, just slower). bake.spec.ts fails when the baked
// string is not what a fresh build produces, so CI catches a stale bake. Outputs go through their
// encoding on the FRESH path too, so a replay is bit-identical to a fresh build. (A side benefit:
// with the decisions baked, every browser builds the same world even where its floats differ.)

/** How an entry's numbers are stored: exact, float32, or fixed point (mm or cm) in 16 bits. */
export type Enc = 'f64' | 'f32' | 'mm16' | 'cm16';

/** Bump when the bake's binary layout changes. */
const FORMAT = 1;

export interface Memo {
  /**
   * A cached decision: replayed when the bake holds `key` computed from the same `inputs`, else
   * computed now. The result always went through `enc` (fresh and replayed builds agree exactly).
   */
  get(key: string, inputs: ArrayLike<number>, compute: () => ArrayLike<number>, enc?: Enc): Float64Array;
  /** The bake string for what this build used (every entry, replayed or fresh). */
  dump(): string;
  readonly stats: { hits: number; misses: number; stale: string[] };
  /** This terrain's fingerprint and the bake's (0: none, or unreadable). */
  readonly fp: { terrain: number; baked: number };
}

interface Entry {
  key: number;
  inputs: number;
  enc: Enc;
  values: Float64Array;
}

const ENCS: Enc[] = ['f64', 'f32', 'mm16', 'cm16'];
const BYTES: Record<Enc, number> = { f64: 8, f32: 4, mm16: 2, cm16: 2 };

/** FNV-1a over a string. */
function hashStr(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

const f64 = new Float64Array(1);
const u32 = new Uint32Array(f64.buffer);
/**
 * FNV-1a over a list of numbers rounded to 1e-6 (JS engines differ in the last bits of Math.sin,
 * pow…: a terrain computed in another browser must still match its bake).
 */
export function hashNums(a: ArrayLike<number>, seed = 0x811c9dc5): number {
  let h = seed;
  for (let i = 0; i < a.length; i++) {
    f64[0] = Math.round(a[i] * 1e6);
    for (let k = 0; k < 2; k++) {
      let w = u32[k];
      for (let b = 0; b < 4; b++) {
        h ^= w & 0xff;
        h = Math.imul(h, 0x01000193);
        w >>>= 8;
      }
    }
  }
  return h >>> 0;
}

/** Round-trip values through an encoding (what a replay would read back). */
function through(v: ArrayLike<number>, enc: Enc): Float64Array {
  const out = new Float64Array(v.length);
  for (let i = 0; i < v.length; i++) {
    const x = v[i];
    out[i] = enc === 'f64' ? x : enc === 'f32' ? Math.fround(x) : enc === 'mm16' ? clamp16(Math.round(x * 1000)) / 1000 : clamp16(Math.round(x * 100)) / 100;
  }
  return out;
}
const clamp16 = (n: number) => (n < -32768 ? -32768 : n > 32767 ? 32767 : n);

// ── base64 (no Buffer / atob dependency: runs in node, the browser and workers alike) ──
const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
function toB64(b: Uint8Array): string {
  let s = '';
  for (let i = 0; i < b.length; i += 3) {
    const n = (b[i] << 16) | ((b[i + 1] ?? 0) << 8) | (b[i + 2] ?? 0);
    s += B64[(n >> 18) & 63] + B64[(n >> 12) & 63] + (i + 1 < b.length ? B64[(n >> 6) & 63] : '=') + (i + 2 < b.length ? B64[n & 63] : '=');
  }
  return s;
}
function fromB64(s: string): Uint8Array {
  const look = new Int16Array(128).fill(-1);
  for (let i = 0; i < 64; i++) look[B64.charCodeAt(i)] = i;
  const n = s.length;
  const pad = s.endsWith('==') ? 2 : s.endsWith('=') ? 1 : 0;
  const out = new Uint8Array((n / 4) * 3 - pad);
  let o = 0;
  for (let i = 0; i < n; i += 4) {
    const v = (look[s.charCodeAt(i)] << 18) | (look[s.charCodeAt(i + 1)] << 12) | ((look[s.charCodeAt(i + 2)] & 63) << 6) | (look[s.charCodeAt(i + 3)] & 63);
    if (o < out.length) out[o++] = (v >> 16) & 255;
    if (o < out.length) out[o++] = (v >> 8) & 255;
    if (o < out.length) out[o++] = v & 255;
  }
  return out;
}

/** Layout: u16 format, u32 fingerprint, u32 count, then per entry u32 key, u32 inputs, u8 enc, u32 n, payload (little endian). */
function encodeAll(fp: number, entries: Entry[]): string {
  let size = 10;
  for (const e of entries) size += 13 + e.values.length * BYTES[e.enc];
  const buf = new ArrayBuffer(size);
  const dv = new DataView(buf);
  let o = 0;
  dv.setUint16(o, FORMAT, true);
  dv.setUint32((o += 2), fp, true);
  dv.setUint32((o += 4), entries.length, true);
  o += 4;
  for (const e of entries) {
    dv.setUint32(o, e.key, true);
    dv.setUint32(o + 4, e.inputs, true);
    dv.setUint8(o + 8, ENCS.indexOf(e.enc));
    dv.setUint32(o + 9, e.values.length, true);
    o += 13;
    for (let i = 0; i < e.values.length; i++) {
      const x = e.values[i];
      if (e.enc === 'f64') dv.setFloat64(o, x, true);
      else if (e.enc === 'f32') dv.setFloat32(o, x, true);
      else dv.setInt16(o, clamp16(Math.round(x * (e.enc === 'mm16' ? 1000 : 100))), true);
      o += BYTES[e.enc];
    }
  }
  return toB64(new Uint8Array(buf));
}

function decodeAll(s: string): { fp: number; entries: Map<number, Entry> } | null {
  try {
    const b = fromB64(s);
    const dv = new DataView(b.buffer, b.byteOffset, b.byteLength);
    if (dv.getUint16(0, true) !== FORMAT) return null;
    const fp = dv.getUint32(2, true);
    const n = dv.getUint32(6, true);
    const entries = new Map<number, Entry>();
    let o = 10;
    for (let k = 0; k < n; k++) {
      const key = dv.getUint32(o, true);
      const inputs = dv.getUint32(o + 4, true);
      const enc = ENCS[dv.getUint8(o + 8)];
      const len = dv.getUint32(o + 9, true);
      o += 13;
      const values = new Float64Array(len);
      for (let i = 0; i < len; i++) {
        values[i] = enc === 'f64' ? dv.getFloat64(o, true) : enc === 'f32' ? dv.getFloat32(o, true) : dv.getInt16(o, true) / (enc === 'mm16' ? 1000 : 100);
        o += BYTES[enc];
      }
      entries.set(key, { key, inputs, enc, values });
    }
    return { fp, entries };
  } catch {
    return null;
  }
}

/** A memo for one build: `fingerprint` of the terrain it runs on, `baked` the stored string (if any). */
export function createMemo(fingerprint: number, baked?: string): Memo {
  const dec = baked ? decodeAll(baked) : null;
  const store = dec && dec.fp === fingerprint ? dec.entries : null;
  const used: Entry[] = [];
  const seen = new Set<number>();
  const stats = { hits: 0, misses: 0, stale: [] as string[] };
  return {
    stats,
    fp: { terrain: fingerprint, baked: dec?.fp ?? 0 },
    get(key, inputs, compute, enc = 'f64') {
      const kh = hashStr(key);
      if (seen.has(kh)) throw new Error(`region memo: duplicate key ${key}`);
      seen.add(kh);
      const ih = hashNums(inputs);
      const hit = store?.get(kh);
      let values: Float64Array;
      if (hit && hit.inputs === ih && hit.enc === enc) {
        values = hit.values;
        stats.hits++;
      } else {
        values = through(compute(), enc);
        stats.misses++;
        if (store) stats.stale.push(key);
      }
      used.push({ key: kh, inputs: ih, enc, values });
      return values;
    },
    dump: () => encodeAll(fingerprint, used),
  };
}
