// The region build's memo (R1): its costly searches (settlement and airport sites, A* routes, terrain
// samples along roads and round pads) are cached decisions. A build for the canonical seed replays
// them from a baked string (world/region/baked.ts, generated by bake.spec.ts) and only does the cheap
// deterministic work itself (towns' streets, smoothing, grading, the network, the carve grid), which
// keeps getRegion() inside its budget on the terrain's first-frame path.
//
// Safety: each entry stores a hash of the INPUTS it was computed from (anchor positions, endpoints,
// the path it sampled…, rounded to 1e-6 so another JS engine's last-bit differences still match) and
// the whole bake a fingerprint of the base terrain; an entry whose inputs differ, or a bake for
// another terrain, is recomputed live (correct, just slower). bake.spec.ts fails when the baked
// string is not what a fresh build produces, so CI catches a stale bake. Outputs go through their
// encoding on the FRESH path too, so a replay is bit-identical to a fresh build. (A side benefit:
// with the decisions baked, every browser builds the same world even where its floats differ.)

/** How an entry's numbers are stored: exact, float32, or fixed point (mm or cm) in 16 bits. */
export type Enc = 'f64' | 'f32' | 'mm16' | 'cm16';

/**
 * Bump when the bake's layout changes. 2 (v2 R2 refine): the 16-bit entries moved out of the binary
 * into a text stream of difference residuals (see `encodeAll`).
 */
const FORMAT = 2;

export interface Memo {
  /**
   * A cached decision: replayed when the bake holds `key` computed from the same `inputs`, else
   * computed now. The result always went through `enc` (fresh and replayed builds agree exactly).
   * v2 (R2 refine 2): `compute` null — a production build, whose searches and planners are compiled
   * out (`process.env.NODE_ENV === 'production' ? null : …`) — replays the baked entry by its key
   * alone (the canonical seed's bake, whatever the inputs' last bits), and throws if there is none.
   */
  get(key: string, inputs: ArrayLike<number>, compute: (() => ArrayLike<number>) | null, enc?: Enc): Float64Array;
  /** The bake string for what this build used (every entry, replayed or fresh). */
  dump(): string;
  readonly stats: { hits: number; misses: number; stale: string[]; drift: Drift[] };
  /** This terrain's fingerprint and the bake's (0: none, or unreadable). */
  readonly fp: { terrain: number; baked: number };
}

/**
 * Verify mode (bake.spec.ts): a replayed entry also recomputed from the same inputs, where the two
 * differ — `len` the baked value count, `got` the recomputed one, `max` their largest difference.
 */
export interface Drift {
  key: string;
  enc: Enc;
  len: number;
  got: number;
  max: number;
}

interface Entry {
  key: number;
  inputs: number;
  enc: Enc;
  values: Float64Array;
}

const ENCS: Enc[] = ['f64', 'f32', 'mm16', 'cm16'];
const BYTES: Record<Enc, number> = { f64: 8, f32: 4, mm16: 2, cm16: 2 };

/** FNV-1a over a string. */
function hashStr(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

const f64 = new Float64Array(1);
const u32 = new Uint32Array(f64.buffer);
/**
 * FNV-1a over a list of numbers rounded to 1e-6 (JS engines differ in the last bits of Math.sin,
 * pow…: a terrain computed in another browser must still match its bake).
 */
export function hashNums(a: ArrayLike<number>, seed = 0x811c9dc5): number {
  let h = seed;
  for (let i = 0; i < a.length; i++) {
    f64[0] = Math.round(a[i] * 1e6);
    for (let k = 0; k < 2; k++) {
      let w = u32[k];
      for (let b = 0; b < 4; b++) {
        h ^= w & 0xff;
        h = Math.imul(h, 0x01000193);
        w >>>= 8;
      }
    }
  }
  return h >>> 0;
}

/** Round-trip values through an encoding (what a replay would read back). */
function through(v: ArrayLike<number>, enc: Enc): Float64Array {
  const out = new Float64Array(v.length);
  for (let i = 0; i < v.length; i++) {
    const x = v[i];
    // (+ 0: a fixed-point value rounding to −0 reads back as +0, and the chain hash tells them apart)
    out[i] = enc === 'f64' ? x : enc === 'f32' ? Math.fround(x) : enc === 'mm16' ? clamp16(Math.round(x * 1000)) / 1000 + 0 : clamp16(Math.round(x * 100)) / 100 + 0;
  }
  return out;
}
const clamp16 = (n: number) => (n < -32768 ? -32768 : n > 32767 ? 32767 : n);

// ── base64 (no Buffer / atob dependency: runs in node, the browser and workers alike) ──
const B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
function toB64(b: Uint8Array): string {
  let s = '';
  for (let i = 0; i < b.length; i += 3) {
    const n = (b[i] << 16) | ((b[i + 1] ?? 0) << 8) | (b[i + 2] ?? 0);
    s += B64[(n >> 18) & 63] + B64[(n >> 12) & 63] + (i + 1 < b.length ? B64[(n >> 6) & 63] : '=') + (i + 2 < b.length ? B64[n & 63] : '=');
  }
  return s;
}
function fromB64(s: string): Uint8Array {
  const look = new Int16Array(128).fill(-1);
  for (let i = 0; i < 64; i++) look[B64.charCodeAt(i)] = i;
  const n = s.length;
  const pad = s.endsWith('==') ? 2 : s.endsWith('=') ? 1 : 0;
  const out = new Uint8Array((n / 4) * 3 - pad);
  let o = 0;
  for (let i = 0; i < n; i += 4) {
    const v = (look[s.charCodeAt(i)] << 18) | (look[s.charCodeAt(i + 1)] << 12) | ((look[s.charCodeAt(i + 2)] & 63) << 6) | (look[s.charCodeAt(i + 3)] & 63);
    if (o < out.length) out[o++] = (v >> 16) & 255;
    if (o < out.length) out[o++] = (v >> 8) & 255;
    if (o < out.length) out[o++] = v & 255;
  }
  return out;
}

// ── the fixed-point entries' stream ──
// A 16-bit entry holds smooth data (centrelines, profiles, skeletons) to the mm or cm: its successive
// differences (of order 1–3, at a stride of 1–3 for interleaved tuples, whichever is shortest) are
// mostly a few units, written as zigzag varints of 5 bits per character. Runs of small residuals are
// what gzip compresses best; the base64 of the raw int16s hardly compressed at all.
const C64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
function residuals(q: ArrayLike<number>, ord: number, st: number): Int32Array {
  const r = Int32Array.from(q);
  for (let o = 0; o < ord; o++) for (let i = r.length - 1; i >= st * (o + 1); i--) r[i] -= r[i - st];
  return r;
}
function varints(r: Int32Array): string {
  let out = '';
  for (let i = 0; i < r.length; i++) {
    let z = ((r[i] << 1) ^ (r[i] >> 31)) >>> 0;
    while (z >= 32) {
      out += C64[32 | (z & 31)];
      z >>>= 5;
    }
    out += C64[z];
  }
  return out;
}

/**
 * Layout: base64 of (u16 format, u32 fingerprint, u32 count, then per entry u32 key, u32 inputs, u8 enc,
 * u32 n, and the payload for f64 / f32, or for mm16 / cm16 a u8 mode = order · 4 + stride), a '.',
 * then the 16-bit entries' residual streams in entry order.
 */
function encodeAll(fp: number, entries: Entry[]): string {
  const is16 = (e: Entry) => e.enc === 'mm16' || e.enc === 'cm16';
  let size = 10;
  for (const e of entries) size += 13 + (is16(e) ? 1 : e.values.length * BYTES[e.enc]);
  const buf = new ArrayBuffer(size);
  const dv = new DataView(buf);
  let o = 0;
  let text = '';
  dv.setUint16(o, FORMAT, true);
  dv.setUint32((o += 2), fp, true);
  dv.setUint32((o += 4), entries.length, true);
  o += 4;
  for (const e of entries) {
    dv.setUint32(o, e.key, true);
    dv.setUint32(o + 4, e.inputs, true);
    dv.setUint8(o + 8, ENCS.indexOf(e.enc));
    dv.setUint32(o + 9, e.values.length, true);
    o += 13;
    if (is16(e)) {
      const sc = e.enc === 'mm16' ? 1000 : 100;
      const q = Array.from(e.values, (x) => clamp16(Math.round(x * sc)));
      let best = '';
      let mode = 0;
      for (let ord = 1; ord <= 3; ord++)
        for (let st = 1; st <= 3; st++) {
          const t = varints(residuals(q, ord, st));
          if (!mode || t.length < best.length) (best = t), (mode = ord * 4 + st);
        }
      dv.setUint8(o, mode);
      o += 1;
      text += best;
      continue;
    }
    for (let i = 0; i < e.values.length; i++) {
      if (e.enc === 'f64') dv.setFloat64(o, e.values[i], true);
      else dv.setFloat32(o, e.values[i], true);
      o += BYTES[e.enc];
    }
  }
  return toB64(new Uint8Array(buf)) + '.' + text;
}

function decodeAll(s: string): { fp: number; entries: Map<number, Entry> } | null {
  try {
    const dot = s.indexOf('.');
    if (dot < 0) return null;
    const b = fromB64(s.slice(0, dot));
    const dv = new DataView(b.buffer, b.byteOffset, b.byteLength);
    if (dv.getUint16(0, true) !== FORMAT) return null;
    const look = new Int8Array(128).fill(-1);
    for (let i = 0; i < 64; i++) look[C64.charCodeAt(i)] = i;
    let t = dot + 1;
    const fp = dv.getUint32(2, true);
    const n = dv.getUint32(6, true);
    const entries = new Map<number, Entry>();
    let o = 10;
    for (let k = 0; k < n; k++) {
      const key = dv.getUint32(o, true);
      const inputs = dv.getUint32(o + 4, true);
      const enc = ENCS[dv.getUint8(o + 8)];
      const len = dv.getUint32(o + 9, true);
      o += 13;
      const values = new Float64Array(len);
      if (enc === 'mm16' || enc === 'cm16') {
        const mode = dv.getUint8(o);
        o += 1;
        const ord = mode >> 2, st = mode & 3;
        const r = new Int32Array(len);
        for (let i = 0; i < len; i++) {
          let z = 0;
          for (let sh = 0; ; sh += 5) {
            const c = look[s.charCodeAt(t++)];
            if (c < 0) return null;
            z += (c & 31) * 2 ** sh;
            if (c < 32) break;
          }
          r[i] = z % 2 ? -(z + 1) / 2 : z / 2;
        }
        for (let q = ord - 1; q >= 0; q--) for (let i = st * (q + 1); i < len; i++) r[i] += r[i - st];
        const sc = enc === 'mm16' ? 1000 : 100;
        for (let i = 0; i < len; i++) values[i] = r[i] / sc + 0;
      } else {
        for (let i = 0; i < len; i++) {
          values[i] = enc === 'f64' ? dv.getFloat64(o, true) : dv.getFloat32(o, true);
          o += BYTES[enc];
        }
      }
      entries.set(key, { key, inputs, enc, values });
    }
    return { fp, entries };
  } catch {
    return null;
  }
}

/**
 * A memo for one build: `fingerprint` of the terrain it runs on, `baked` the stored string (if any).
 * `verify` (bake.spec.ts) also recomputes every replayed entry from the same inputs and records where
 * the two differ (stats.drift): the replay still decides, so every later input stays the bake's.
 */
export function createMemo(fingerprint: number, baked?: string, verify = false): Memo {
  const dec = baked ? decodeAll(baked) : null;
  const store = dec && dec.fp === fingerprint ? dec.entries : null;
  const used: Entry[] = [];
  const seen = new Set<number>();
  const stats = { hits: 0, misses: 0, stale: [] as string[], drift: [] as Drift[] };
  return {
    stats,
    fp: { terrain: fingerprint, baked: dec?.fp ?? 0 },
    get(key, inputs, compute, enc = 'f64') {
      const kh = hashStr(key);
      if (seen.has(kh)) throw new Error(`region memo: duplicate key ${key}`);
      seen.add(kh);
      const ih = hashNums(inputs);
      const hit = store?.get(kh);
      let values: Float64Array;
      if (hit && hit.enc === enc && (hit.inputs === ih || !compute)) {
        values = hit.values;
        stats.hits++;
        if (verify && compute) {
          const got = through(compute(), enc);
          let max = got.length === values.length ? 0 : Infinity;
          for (let i = 0; i < got.length && i < values.length; i++) max = Math.max(max, Math.abs(got[i] - values[i]));
          if (max > 0) stats.drift.push({ key, enc, len: values.length, got: got.length, max });
        }
      } else if (!compute) {
        throw new Error(`region: no baked ${key} (regenerate world/region/baked.ts)`);
      } else {
        values = through(compute(), enc);
        stats.misses++;
        if (store) stats.stale.push(key);
      }
      used.push({ key: kh, inputs: ih, enc, values });
      return values;
    },
    // (the bake writer: bake.spec.ts only, compiled out of a production build)
    dump: process.env.NODE_ENV === 'production' ? () => '' : () => encodeAll(fingerprint, used),
  };
}
